# Generated by Django 3.0.3 on 2020-03-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Enquiry_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
