# Generated by Django 3.0.3 on 2020-04-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_discription', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
