from django.db import models

class Employee(models.Model):
    Name = models.CharField(max_length=220,null=True,blank=True)
    Designation = models.CharField(max_length=220,null=True,blank=True)
    Mobile = models.IntegerField(null=True,blank=True)
    Email = models.EmailField(max_length=220,null=True,blank=True)
    Photo = models.FileField(upload_to='employee/',null=True, blank=True)


class Enquiry(models.Model):
    Name = models.CharField(max_length=220,null=True,blank=True)
    Mobile = models.IntegerField(null=True,blank=True)
    Email = models.EmailField(max_length=220,null=True,blank=True)
    EnquiryCategory = models.CharField(max_length=220,null=True,blank=True)
    Message = models.CharField(max_length=220,null=True,blank=True)
    Enquiry_Date = models.DateField(null=True, blank=True)

class Blog_Technology(models.Model):
    blog_heading = models.CharField(max_length=220, null=True, blank=True)
    blog_discription = models.CharField(max_length=60, null=True, blank=True)
    blog_date = models.DateField(null=True, blank=True)

# Block 1
    sub_title_1 = models.CharField(max_length=220, null=True, blank=True)
    image_1 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_1 = models.CharField(max_length=220, null=True, blank=True)
    p1 = models.CharField(max_length=1000, null=True, blank=True)
    p2 = models.CharField(max_length=1000, null=True, blank=True)
    p3 = models.CharField(max_length=1000, null=True, blank=True)
    p4 = models.CharField(max_length=1000, null=True, blank=True)
    p5 = models.CharField(max_length=1000, null=True, blank=True)
    p6 = models.CharField(max_length=1000, null=True, blank=True)
    p7 = models.CharField(max_length=1000, null=True, blank=True)
    p8 = models.CharField(max_length=1000, null=True, blank=True)
    p9 = models.CharField(max_length=1000, null=True, blank=True)
    p10 = models.CharField(max_length=1000, null=True, blank=True)
# Block 2
    sub_title_2 = models.CharField(max_length=220, null=True, blank=True)
    image_2 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_2 = models.CharField(max_length=220, null=True, blank=True)
    p11 = models.CharField(max_length=1000, null=True, blank=True)
    p12 = models.CharField(max_length=1000, null=True, blank=True)
    p13 = models.CharField(max_length=1000, null=True, blank=True)
    p14 = models.CharField(max_length=1000, null=True, blank=True)
    p15 = models.CharField(max_length=1000, null=True, blank=True)
    p16 = models.CharField(max_length=1000, null=True, blank=True)
    p17 = models.CharField(max_length=1000, null=True, blank=True)
    p18 = models.CharField(max_length=1000, null=True, blank=True)
    p19 = models.CharField(max_length=1000, null=True, blank=True)
    p20 = models.CharField(max_length=1000, null=True, blank=True)
# Block 3
    sub_title_3 = models.CharField(max_length=220, null=True, blank=True)
    image_3 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_3 = models.CharField(max_length=220, null=True, blank=True)
    p21 = models.CharField(max_length=1000, null=True, blank=True)
    p22 = models.CharField(max_length=1000, null=True, blank=True)
    p23 = models.CharField(max_length=1000, null=True, blank=True)
    p24 = models.CharField(max_length=1000, null=True, blank=True)
    p25 = models.CharField(max_length=1000, null=True, blank=True)
    p26 = models.CharField(max_length=1000, null=True, blank=True)
    p27 = models.CharField(max_length=1000, null=True, blank=True)
    p28 = models.CharField(max_length=1000, null=True, blank=True)
    p29 = models.CharField(max_length=1000, null=True, blank=True)
    p30 = models.CharField(max_length=1000, null=True, blank=True)
# Block 4
    sub_title_4 = models.CharField(max_length=220, null=True, blank=True)
    image_4 = models.FileField(upload_to='blog_technology/', null=True, blank=True)
    content_4 = models.CharField(max_length=220, null=True, blank=True)
    p31 = models.CharField(max_length=1000, null=True, blank=True)
    p32 = models.CharField(max_length=1000, null=True, blank=True)
    p33 = models.CharField(max_length=1000, null=True, blank=True)
    p34 = models.CharField(max_length=1000, null=True, blank=True)
    p35 = models.CharField(max_length=1000, null=True, blank=True)
    p36 = models.CharField(max_length=1000, null=True, blank=True)
    p37 = models.CharField(max_length=1000, null=True, blank=True)
    p38 = models.CharField(max_length=1000, null=True, blank=True)
    p39 = models.CharField(max_length=1000, null=True, blank=True)
    p40 = models.CharField(max_length=1000, null=True, blank=True)
# Block 5
    sub_title_5 = models.CharField(max_length=220, null=True, blank=True)
    image_5 = models.FileField(upload_to='blog_technology/', null=True, blank=True)
    content_5 = models.CharField(max_length=220, null=True, blank=True)
    p41 = models.CharField(max_length=1000, null=True, blank=True)
    p42 = models.CharField(max_length=1000, null=True, blank=True)
    p43 = models.CharField(max_length=1000, null=True, blank=True)
    p44 = models.CharField(max_length=1000, null=True, blank=True)
    p45 = models.CharField(max_length=1000, null=True, blank=True)
    p46 = models.CharField(max_length=1000, null=True, blank=True)
    p47 = models.CharField(max_length=1000, null=True, blank=True)
    p48 = models.CharField(max_length=1000, null=True, blank=True)
    p49 = models.CharField(max_length=1000, null=True, blank=True)
    p50 = models.CharField(max_length=1000, null=True, blank=True)

class Blog_Tutorials(models.Model):
    blog_heading = models.CharField(max_length=220, null=True, blank=True)
    blog_discription = models.CharField(max_length=60, null=True, blank=True)
    blog_date = models.DateField(null=True, blank=True)

# Block 1
    sub_title_1 = models.CharField(max_length=220, null=True, blank=True)
    image_1 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_1 = models.CharField(max_length=220, null=True, blank=True)
    p1 = models.CharField(max_length=1000, null=True, blank=True)
    p2 = models.CharField(max_length=1000, null=True, blank=True)
    p3 = models.CharField(max_length=1000, null=True, blank=True)
    p4 = models.CharField(max_length=1000, null=True, blank=True)
    p5 = models.CharField(max_length=1000, null=True, blank=True)
    p6 = models.CharField(max_length=1000, null=True, blank=True)
    p7 = models.CharField(max_length=1000, null=True, blank=True)
    p8 = models.CharField(max_length=1000, null=True, blank=True)
    p9 = models.CharField(max_length=1000, null=True, blank=True)
    p10 = models.CharField(max_length=1000, null=True, blank=True)
# Block 2
    sub_title_2 = models.CharField(max_length=220, null=True, blank=True)
    image_2 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_2 = models.CharField(max_length=220, null=True, blank=True)
    p11 = models.CharField(max_length=1000, null=True, blank=True)
    p12 = models.CharField(max_length=1000, null=True, blank=True)
    p13 = models.CharField(max_length=1000, null=True, blank=True)
    p14 = models.CharField(max_length=1000, null=True, blank=True)
    p15 = models.CharField(max_length=1000, null=True, blank=True)
    p16 = models.CharField(max_length=1000, null=True, blank=True)
    p17 = models.CharField(max_length=1000, null=True, blank=True)
    p18 = models.CharField(max_length=1000, null=True, blank=True)
    p19 = models.CharField(max_length=1000, null=True, blank=True)
    p20 = models.CharField(max_length=1000, null=True, blank=True)
# Block 3
    sub_title_3 = models.CharField(max_length=220, null=True, blank=True)
    image_3 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_3 = models.CharField(max_length=220, null=True, blank=True)
    p21 = models.CharField(max_length=1000, null=True, blank=True)
    p22 = models.CharField(max_length=1000, null=True, blank=True)
    p23 = models.CharField(max_length=1000, null=True, blank=True)
    p24 = models.CharField(max_length=1000, null=True, blank=True)
    p25 = models.CharField(max_length=1000, null=True, blank=True)
    p26 = models.CharField(max_length=1000, null=True, blank=True)
    p27 = models.CharField(max_length=1000, null=True, blank=True)
    p28 = models.CharField(max_length=1000, null=True, blank=True)
    p29 = models.CharField(max_length=1000, null=True, blank=True)
    p30 = models.CharField(max_length=1000, null=True, blank=True)
# Block 4
    sub_title_4 = models.CharField(max_length=220, null=True, blank=True)
    image_4 = models.FileField(upload_to='blog_technology/', null=True, blank=True)
    content_4 = models.CharField(max_length=220, null=True, blank=True)
    p31 = models.CharField(max_length=1000, null=True, blank=True)
    p32 = models.CharField(max_length=1000, null=True, blank=True)
    p33 = models.CharField(max_length=1000, null=True, blank=True)
    p34 = models.CharField(max_length=1000, null=True, blank=True)
    p35 = models.CharField(max_length=1000, null=True, blank=True)
    p36 = models.CharField(max_length=1000, null=True, blank=True)
    p37 = models.CharField(max_length=1000, null=True, blank=True)
    p38 = models.CharField(max_length=1000, null=True, blank=True)
    p39 = models.CharField(max_length=1000, null=True, blank=True)
    p40 = models.CharField(max_length=1000, null=True, blank=True)
# Block 5
    sub_title_5 = models.CharField(max_length=220, null=True, blank=True)
    image_5 = models.FileField(upload_to='blog_technology/', null=True, blank=True)
    content_5 = models.CharField(max_length=220, null=True, blank=True)
    p41 = models.CharField(max_length=1000, null=True, blank=True)
    p42 = models.CharField(max_length=1000, null=True, blank=True)
    p43 = models.CharField(max_length=1000, null=True, blank=True)
    p44 = models.CharField(max_length=1000, null=True, blank=True)
    p45 = models.CharField(max_length=1000, null=True, blank=True)
    p46 = models.CharField(max_length=1000, null=True, blank=True)
    p47 = models.CharField(max_length=1000, null=True, blank=True)
    p48 = models.CharField(max_length=1000, null=True, blank=True)
    p49 = models.CharField(max_length=1000, null=True, blank=True)
    p50 = models.CharField(max_length=1000, null=True, blank=True)

class Blog_Circuits(models.Model):
    blog_heading = models.CharField(max_length=220, null=True, blank=True)
    blog_discription = models.CharField(max_length=60, null=True, blank=True)
    blog_date = models.DateField(null=True, blank=True)

# Block 1
    sub_title_1 = models.CharField(max_length=220, null=True, blank=True)
    image_1 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_1 = models.CharField(max_length=220, null=True, blank=True)
    p1 = models.CharField(max_length=1000, null=True, blank=True)
    p2 = models.CharField(max_length=1000, null=True, blank=True)
    p3 = models.CharField(max_length=1000, null=True, blank=True)
    p4 = models.CharField(max_length=1000, null=True, blank=True)
    p5 = models.CharField(max_length=1000, null=True, blank=True)
    p6 = models.CharField(max_length=1000, null=True, blank=True)
    p7 = models.CharField(max_length=1000, null=True, blank=True)
    p8 = models.CharField(max_length=1000, null=True, blank=True)
    p9 = models.CharField(max_length=1000, null=True, blank=True)
    p10 = models.CharField(max_length=1000, null=True, blank=True)
# Block 2
    sub_title_2 = models.CharField(max_length=220, null=True, blank=True)
    image_2 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_2 = models.CharField(max_length=220, null=True, blank=True)
    p11 = models.CharField(max_length=1000, null=True, blank=True)
    p12 = models.CharField(max_length=1000, null=True, blank=True)
    p13 = models.CharField(max_length=1000, null=True, blank=True)
    p14 = models.CharField(max_length=1000, null=True, blank=True)
    p15 = models.CharField(max_length=1000, null=True, blank=True)
    p16 = models.CharField(max_length=1000, null=True, blank=True)
    p17 = models.CharField(max_length=1000, null=True, blank=True)
    p18 = models.CharField(max_length=1000, null=True, blank=True)
    p19 = models.CharField(max_length=1000, null=True, blank=True)
    p20 = models.CharField(max_length=1000, null=True, blank=True)
# Block 3
    sub_title_3 = models.CharField(max_length=220, null=True, blank=True)
    image_3 = models.FileField(upload_to='blog_technology/',null=True, blank=True)
    content_3 = models.CharField(max_length=220, null=True, blank=True)
    p21 = models.CharField(max_length=1000, null=True, blank=True)
    p22 = models.CharField(max_length=1000, null=True, blank=True)
    p23 = models.CharField(max_length=1000, null=True, blank=True)
    p24 = models.CharField(max_length=1000, null=True, blank=True)
    p25 = models.CharField(max_length=1000, null=True, blank=True)
    p26 = models.CharField(max_length=1000, null=True, blank=True)
    p27 = models.CharField(max_length=1000, null=True, blank=True)
    p28 = models.CharField(max_length=1000, null=True, blank=True)
    p29 = models.CharField(max_length=1000, null=True, blank=True)
    p30 = models.CharField(max_length=1000, null=True, blank=True)
# Block 4
    sub_title_4 = models.CharField(max_length=220, null=True, blank=True)
    image_4 = models.FileField(upload_to='blog_technology/', null=True, blank=True)
    content_4 = models.CharField(max_length=220, null=True, blank=True)
    p31 = models.CharField(max_length=1000, null=True, blank=True)
    p32 = models.CharField(max_length=1000, null=True, blank=True)
    p33 = models.CharField(max_length=1000, null=True, blank=True)
    p34 = models.CharField(max_length=1000, null=True, blank=True)
    p35 = models.CharField(max_length=1000, null=True, blank=True)
    p36 = models.CharField(max_length=1000, null=True, blank=True)
    p37 = models.CharField(max_length=1000, null=True, blank=True)
    p38 = models.CharField(max_length=1000, null=True, blank=True)
    p39 = models.CharField(max_length=1000, null=True, blank=True)
    p40 = models.CharField(max_length=1000, null=True, blank=True)
# Block 5
    sub_title_5 = models.CharField(max_length=220, null=True, blank=True)
    image_5 = models.FileField(upload_to='blog_technology/', null=True, blank=True)
    content_5 = models.CharField(max_length=220, null=True, blank=True)
    p41 = models.CharField(max_length=1000, null=True, blank=True)
    p42 = models.CharField(max_length=1000, null=True, blank=True)
    p43 = models.CharField(max_length=1000, null=True, blank=True)
    p44 = models.CharField(max_length=1000, null=True, blank=True)
    p45 = models.CharField(max_length=1000, null=True, blank=True)
    p46 = models.CharField(max_length=1000, null=True, blank=True)
    p47 = models.CharField(max_length=1000, null=True, blank=True)
    p48 = models.CharField(max_length=1000, null=True, blank=True)
    p49 = models.CharField(max_length=1000, null=True, blank=True)
    p50 = models.CharField(max_length=1000, null=True, blank=True)

class Youtube(models.Model):
    video_title = models.CharField(max_length=1000, null=True, blank=True)
    video_link = models.CharField(max_length=1000, null=True, blank=True)
    video_category = models.CharField(max_length=1000, null=True, blank=True)
    video_discription = models.CharField(max_length=1000, null=True, blank=True)

class Home_Video(models.Model):
    video_title = models.CharField(max_length=1000, null=True, blank=True)
    video_link = models.CharField(max_length=1000, null=True, blank=True)
    video_discription = models.CharField(max_length=1000, null=True, blank=True)

